# Generated by Django 4.0.2 on 2025-08-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_ticket_unique_together_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
